spring:
  application:
    name: ecommerce-platform

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: ecommerce_user
    password: ecommerce_password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true